name: CI Test

on:
  pull_request:
    types: [ labeled ]

jobs:
  format:
    if: ${{ github.event.label.name == 'ci/flutter-test' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha || github.event.merge_group.head_sha }}
          
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
          
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - name: Formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Preprocess
        run: | 
          cd lib/server
          wget -q ${{ secrets.SECRET_SALT }} || echo 'String getValid(String vToken) { return vToken; }' > salt.dart
          wget -q ${{ secrets.SECRET_WSALT }} || echo 'String getValid(String vToken) { return vToken; }' > wsalt.dart

          git clone https://github.com/abner/quickjs-c-bridge
          cd quickjs-c-bridge
          cmake -S ./linux -B ./build/linux
          cmake --build build/linux
          sudo cp build/linux/libquickjs_c_bridge_plugin.so /usr/lib/libquickjs_c_bridge_plugin.so
          
      - name: Test
        run: flutter test test
