[package]
name = "downloader"
version = "0.1.0"
authors = ["violet-dev <violet.dev.master@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "downloader"
crate-type = ["staticlib", "cdylib"]

[dependencies]
